// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `prisma generate` runs in environments WITHOUT a database (Vercel/CI
// postinstall), so a missing URL must warn rather than hard-fail here.
// Connection-requiring commands (migrate deploy / db seed) will surface
// their own clear connection error immediately after this warning prints.
const datasourceUrl = process.env.DATABASE_URL ?? "";

if (!datasourceUrl) {
  console.warn(
    "⚠️  DATABASE_URL is not set. Schema-only commands (generate) work, " +
      "but migrate/seed need a PostgreSQL connection string from .env"
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node ./prisma/seed.mjs",
  },
  datasource: {
    url: datasourceUrl,
  },
});
